### PR TITLE
"Sync customization specifications during cloud sync for vSphere asyn…

### PR DESCRIPTION
**Pull request by gvijayakuma2**
SDK Changes for supporting custom policies during sync for vSphere adapter

### CODE REVIEW

**Comment by gvijayakuma2** [comment]
@mark-a-johnson for review

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/61/

**Comment by mark-a-johnson** [comment]
You need to bump the version of the SDK.  I believe there's an overall version number for the open source projects.

Also, I don't think there's an auto-merge so these same changes are needed for the develop branch.

**Comment by Behnke19** [comment]
@mark-a-johnson The version is bumped automatically when the build happens.

**Pull request merged**
