### PR TITLE
[US2188] : made uniform versoin for all modules; auto generating manifest files

### PR DESCRIPTION
**Pull request by sappalaneni2**
. made uniform version for all modules; 
. auto generating manifest files

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/8/

**Comment by Behnke19** [comment]
retest

**Comment by msammeta** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/10/

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/11/

**Comment by Behnke19** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/12/

**Comment by sappalaneni2** [comment]
retest

**Pull request merged**
