### PR TITLE
Update manifest files so agility bundles resolve

### PR DESCRIPTION
**Pull request by Behnke19**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/36/

**Comment by msammeta** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/37/

**Comment by msammeta** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/38/

**Comment by sappalaneni2** [comment]
Looks good.

**Pull request merged**
