### PR TITLE
changed releaseManager.xsd for ArtifactoryResponse xml changes

### PR DESCRIPTION
**Pull request by Behnke19**

### CODE REVIEW

**Comment by Behnke19** [comment]
This is a cherry pick to develop that was missed

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/127/

**Comment by Behnke19** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/128/

**Pull request merged**
