### PR TITLE
-- Getting the proxies from the Cloud .

### PR DESCRIPTION
**Pull request by suprakashduttaSM**
request was not giving any proxy details . Hence getting the proxy details directly from cloud .

@rafsanchez @Behnke19 Requesting your review .

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/72/

**Comment by Behnke19** [comment]
Just double checking... Is this supposed to be a part of release-10.2.5? I think 10.2.5 is in code freeze prior to release. Maybe this should be merged to develop-10.2 (10.2.6)?

**Comment by suprakashduttaSM** [comment]
@Behnke19  We are almost done with Swarm Service Adapter and this change is required for using Proxy . As per the details we got from our PO( Khushboo ) yesterday  since  10.2.5 is a maintenance release and its getting wrapped up by Dec 2 so we are putting this change in 10.2.5 release itself. We will be certifying Swarm Service Adapter with AP 10.2.5 . Also this can be used by all other service adapters as well going forward .

**Comment by Behnke19** [comment]
Sounds good. Thanks for the background info. Don't forget to cherry pick this to the develop-10.2 and develop branches

**Comment by suprakashduttaSM** [comment]
@Behnke19  Sure !! Im gonna do that . Also I'm gonna update the versions.xml in agility private repo (release-10.2.5 branch) to get this updated version there as well .

**Pull request merged**
