### PR TITLE
No longer require the presence of distributed.sync.cfg to initialize …

### PR DESCRIPTION
**Pull request by jalopez11**
…zookeeper

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/121/

**Comment by jalopez11** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/122/

**Comment by jalopez11** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/123/

**Comment by jalopez11** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/124/

**Comment by jalopez11** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/125/

**Pull request merged**
