### PR TITLE
modified IArtifactRepository for changes related to publish artifacts

### PR DESCRIPTION
**Pull request by amakhija3**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/116/

**Comment by Behnke19** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/117/

**Comment by Behnke19** [comment]
Please cherry-pick to develop branch

**Pull request merged**
