### PR TITLE
[US2188]: removed local maven repo.

### PR DESCRIPTION
**Pull request by sappalaneni2**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/4/

**Comment by msammeta** [comment]
Test Jenkins build

**Comment by msammeta** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/5/

**Comment by msammeta** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/6/

**Comment by msammeta** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/7/

**Pull request merged**
