### PR TITLE
for TA21037 Getting the list of builds

### PR DESCRIPTION
**Pull request by mpsingh**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/130/

**Comment by Behnke19** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/131/

**Comment by mpsingh** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/132/

**Comment by Behnke19** [comment]
please cherry pick to develop branch

**Pull request merged**
