### PR TITLE
Sync with agility 10.2 aef794f362e8696caea0127dd39dfa67f5258d16

### PR DESCRIPTION
**Pull request by Behnke19**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/39/

**Comment by servicemesh-autobuild** [comment]
:x: Build failed

http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/40/

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/csc-agility-platform-sdk-prb/41/

**Comment by sappalaneni2** [comment]
Looks good.

**Pull request merged**
